### PR TITLE
Refactor services

### PR DESCRIPTION
**Pull request by alyphen**
The primary idea behind this PR is to move away from static, lazily-initialised singletons in favour reference-passing.

Following this approach revealed some cyclic dependencies between services, and upon further discussion about config migration and backwards compatibility, we came to the decision that maintaining backwards compatibility with pre-1.9 was not necessary due to breaking changes in 2.0. The config could also be restructured entirely for a 3.0 reboot that allowed more flexibility in design.

Configuration no longer uses the "configuration cache", as plugins hold their configuration in-memory while they are running anyway.

In addition, a lot of dead code has been removed, and times are now using solely the new Java time APIs as opposed to the older Date and Calendar APIs.

Care has been taken to maintain compatibility with the date and lore formats used in earlier versions of the plugin, but more configuration has been added to this, allowing for non-US formats to be used (such as yyyy-MM-dd or dd/MM/yyyy)

Dan: Please read carefully through this, there's a lot going on and I'd love for you to have a full understanding of it (and to question any design decisions I make!)
There are likely to be mistakes due to the scale of the change, but I believe it brings the codebase into a better state, especially with regards to clarity around configuration.
There are still things left out of scope of this PR (such as bringing logging into a better state, a full relook at command handling, and looking at the ways FoodSpoilage handles events in comparison to rpk-food)

### CODE REVIEW

**Review by dmccoystephenson — APPROVED** [review]
These changes look great! Thank you very much for your contribution.

**Comment by dmccoystephenson** [comment]
One question I do have: Will server owners need to delete the old config.yml in order to run 3.0?

**Comment by alyphen** [comment]
> One question I do have: Will server owners need to delete the old config.yml in order to run 3.0?

As it stands server owners won't have a config.yml at all, at least for the last two versions of 2.x.
Do we know when the last working version was? It might be worth adding a little migration code if we want a smoother upgrade experience.

**Comment by dmccoystephenson** [comment]
> > One question I do have: Will server owners need to delete the old config.yml in order to run 3.0?
> 
> As it stands server owners won't have a config.yml at all, at least for the last two versions of 2.x. Do we know when the last working version was? It might be worth adding a little migration code if we want a smoother upgrade experience.

I think 1.9 was working. Yeah I think that might be worthwhile.

**Pull request merged**
